Gateway:
  route:
    base: "/api/v1"
    endpoints:
      register: "/register"
      login: "/login"
      logout: "/logout"
      create_order: "/order/create"
      get_orders: "/order/get"
      get_order: "/order/{order_id}/get"
      delete_order: "/order/{order_id}/delete"
      status_order: "/order/{order_id}/status"
      history_order: "/order/{order_id}/history"
  server:
    port: ":8080"

Authentication:
  route:
    base: "/v1/auth"
    endpoints:
      register: "/register"
      login: "/login"
      logout: "/logout"
  server:
    port: ":8081"

Order:
  route:
    base: "/v1/order"
    endpoints:
      create_order: "/create"
      get_orders: "/get"
      get_order: "/{order_id}/get"
      delete_order: "/{order_id}/delete"
  server:
    port: ":8082"

Status:
  route:
    base: "/v1/status"
    endpoints:
      status_order: "/{order_id}"
  server:
    port: ":8083"

Payment:
  route:
    base: "/v1/payment"
    endpoints:
      pay_payment: "/{order_id}/pay"
      status_payment: "/{order_id}/status"
  server:
    port: ":8084"

History:
  route:
    base: "/v1/history"
    endpoints:
      history_order: "/{order_id}"
  server:
    port: ":8085"
